name: Tests and Lint

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

env:
  NODE_VERSION: 18

jobs:
  linting:
    name: Tests+Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Run Test
        run: npm test
